spring:
  application:
    name: ecommerce
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: mypassword
    hikari:
      auto-commit: false
      connection-timeout: 250
      max-lifetime: 600000
      maximum-pool-size: 20
      minimum-idle: 10
      pool-name: master
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      "[hibernate.generate_statistics]": false
      "[hibernate.connection.provider_disables_autocommit]": true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
    drop-first: false